### ISSUE TITLE
push to dockerhub

### ISSUE THREAD

**Issue by casperdcl** [stfc/cloud-docker-images#27]
we currently login to both harbour and dockerhub -- in the latter case purely to raise rate limits https://github.com/stfc/cloud-docker-images/blob/3a83ca7292cf72cbf0c9daab50d4e4f25249e499/.github/workflows/build_images.yaml#L34

However can we use the existing credentials to push (at least some images) to dockerhub? (For external users who don't have access to harbour)

**Comment by khalford** [comment]
All images built in this repository are pushed to public projects on Harbour in the `stfc-cloud` project. These can be pulled by anyone and do not require authenitcation.
